const mongoose = require('mongoose');

const ApplicationSchema = new mongoose.Schema(
  {
    fullName:          { type: String },
    applicationId:     { type: String, unique: true, sparse: true },
    workhubCardId:     { type: Number, default: null },
    nicNo:             { type: String },
    passportNo:        { type: String },
    dateOfBirth:       { type: String },
    gender:            { type: String },
    maritalStatus:     { type: String },
    nationality:       { type: String },
    residentialStatus: { type: String },
    permanentAddress:  { type: String },
    mailingAddress:    { type: String },
    yearsAtAbove:      { type: Number },
    monthsAtAbove:     { type: Number },
    homeContact:       { type: String },
    officeContact:     { type: String },
    fax:               { type: String },
    mobile1:           { type: String },
    mobile2:           { type: String },
    email:             { type: String },
    noOfChildren:      { type: Number },
    childAge1:         { type: Number },
    childAge2:         { type: Number },
    childAge3:         { type: Number },
    totalDependants:   { type: Number },
    qualifications:    [String],
    otherQualification:{ type: String },
    familyMembers: [
      {
        member:  { type: String },
        name:    { type: String },
        contact: { type: String },
      },
    ],
    bankDetails: [
      {
        bank:      { type: String },
        branch:    { type: String },
        accountNo: { type: String },
        officer:   { type: String },
        telephone: { type: String },
      },
    ],
    creditFacilities: [
      {
        institution:      { type: String },
        type:             { type: String },
        approvedAmount:   { type: String },
        term:             { type: String },
        monthlyRepayment: { type: String },
        presentOS:        { type: String },
        security:         { type: String },
      },
    ],
    reference1Name:       { type: String },
    reference1Profession: { type: String },
    reference1Contact:    { type: String },
    reference2Name:       { type: String },
    reference2Profession: { type: String },
    reference2Contact:    { type: String },
    employerBusinessName:    { type: String },
    employerBusinessAddress: { type: String },
    natureOfBusiness:        { type: String },
    designationProfession:   { type: String },
    telephone:   { type: String },
    designation: { type: String },
    employmentProfessionalBusiness: { type: String },
    specificIncomeSource:    { type: String },
    additionalIncomeSources: { type: String },
    liableForTax: { type: String },
    taxFileNo:    { type: String },
    incomeMainSalary:      { type: Number },
    incomeOtherAllowances: { type: Number },
    incomeAdditional:      { type: Number },
    incomeOther:           { type: Number },
    expenseHousehold:  { type: Number },
    expensePersonal:   { type: Number },
    expenseLoanLease:  { type: Number },
    expenseCreditCard: { type: Number },
    expenseFuel:       { type: Number },
    expenseOther:      { type: Number },
    guarantors: [
      {
        fullName:         { type: String },
        relationship:     { type: String },
        nicBusinessRegNo: { type: String },
        age:              { type: Number },
        months:           { type: Number },
      },
    ],
    landBuildings: [
      {
        location:  { type: String },
        extent:    { type: String },
        value:     { type: String },
        deedNo:    { type: String },
        mortgaged: { type: String },
      },
    ],
    vehicles: [
      {
        makeModel:  { type: String },
        value:      { type: String },
        regNo:      { type: String },
        ownership:  { type: String },
      },
    ],
    shares: [
      {
        institution:  { type: String },
        currentValue: { type: String },
        noOfShares:   { type: String },
      },
    ],
    lifeInsurance:        { type: String },
    lifeInsuranceSpecify: { type: String },
    deposits:             { type: String },
    depositsSpecify:      { type: String },
    facilityRequirements: [
      {
        makeModel: { type: String },
        status:    { type: String },
        purpose:   { type: String },
        supplier:  { type: String },
        period:    { type: String },
        cost:      { type: String },
      },
    ],
    preferredLanguage:     { type: String },
    locationOfLeasedAsset: { type: String },
    fundSources:           [String],
    otherFundSource:       { type: String },
    annualTurnoverIndividual: { type: String },
    annualTurnoverBusiness:   { type: String },
    otherConnectedBusiness:   { type: String },
    reasonForLoan:            { type: String },
    withinBranchServiceArea:  { type: String },
    ifNoReason:               { type: String },
    isPEP:                    { type: String },
    pepRelationship:          { type: String },
    signatureName:            { type: String },
    signatureDate:            { type: String },
    submittedAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Application', ApplicationSchema);
